package CalculatorApp;


/**
* CalculatorApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* viernes 31 de marzo de 2023 12:06:42 PM COT
*/

public interface CalculatorOperations 
{
  String calcMonthlyFee (double purchase, double MonthlyFee);
} // interface CalculatorOperations
